thread 'main' panicked at '`async fn` resumed after completion', ui/async-await/issues/issue-65419/issue-65419-async-fn-resume-after-completion.rs:12:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
